DELIM=" "
printf "$(TZ=":Etc/UTC" date +"%H:%M")<span foreground='grey'>+0</span>"
printf "$DELIM"
#printf "$(TZ=":Europe/Copenhagen" date +"%H:%M")<span foreground='grey'>+1</span>"
#printf "$DELIM"
printf "$(TZ=":Africa/Johannesburg" date +"%H:%M")<span foreground='grey'>+2</span>"
printf "$DELIM"
#printf "$(TZ=":Indian/Cocos" date +"%H:%M")<span foreground='grey'>+6.5</span>"
#printf "$DELIM"
printf "$(TZ=":Asia/Manila" date +"%H:%M")<span foreground='grey'>+8</span>"
